sorintlab/stolon

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- pkg/cluster/clusterview.go
Deducing the master from an empty follow entry is not enough. In future
old master will be set to follow the new master only when the new master has
converged to the new cluster view (to avoid old master resetting itself and
failing to follow the new master). For doing this multiple members can have an
empty follow entry.
> cluster: add entry to clusterview for defining current master.

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/clusterview.go
Now updateClusterView changes members follow id only when the master is
converged to the current clusterview.
This avoids members dropping their database and trying to sync (pg_basebackup)
to new master if this is not ready since it can bring to a state where no
members have data if the new elected master cannot promote itself or dies
before promoting.
Additionally it always returns a clusterView also if nothing has changed from
the previous one.
> sentinel: updateClusterView: update follow id only if master converged.

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/config.go
- pkg/cluster/config_test.go
- pkg/etcd/etcd.go
* read and update cluster config from etcd at evry keeper and sentinel loop.
Missing:
* reconfiguration of new PGReplUser and PGReplPassword.
Additionally:
* LeaseTTL has been removed from cluster config. Now it's calculated using the
values of sleepInterval and requestTimeout.
> cluster: basic read and update cluster config from etcd.

- cmd/sentinel/sentinel.go
- pkg/cluster/clusterview.go
This is useful for accessing them directly without the need to keep it in
another variable.
> cluster: save member ID in memberState and memberRole structs.

- pkg/cluster/member.go
In the timeline history file the lsn is where the timeline switched. Calling it
"start" is quite confusing.
> cluster: rename timeline "Start" to "Switchpoint"

- cmd/sentinel/sentinel.go
Before reading the values in PGState, GetBestStandby should check if PGState is
nil. This can happen if a new member appears but its PGState isn't available
(because the db is not yet completely started).
> sentinel: check nil PGState.

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
Do not choose a member as the first cluster member if its PGState is unknown.
> sentinel: check nil PGState in cluster initialization.

- cmd/sentinel/sentinel.go
m.PGState.XLogPos was compared with itself instead of the current best
slave.
> sentinel: fix XlogPos check in GetBestSlave

- cmd/keeper/keeper.go
- pkg/cluster/member.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- pkg/postgresql/utils_test.go
- tests/integration/ha_test.go
If a standby is elected as the new master, the other standbys will switch syncing
to the new master. If for any reasons the elected standby was behind other standbys
it will fork a new timeline before the other standbys. The other standbys cannot
sync with it but will need a full resync (pg_basebackup at the moment).
> keeper: check if master timeline is forked before our position.

- README.md
- cmd/keeper/keeper.go
- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- common/common.go
- doc/syncrepl.md
- pkg/cluster/clusterview.go
- pkg/cluster/config.go
- pkg/cluster/config_test.go
- pkg/etcd/etcd.go
- pkg/postgresql/postgresql.go
- test
- tests/integration/ha_test.go
- tests/integration/utils.go
Now users can define in the cluster config if they want synchronous
replication. When enabled the master server parameter `synchronous_standby_names`
will be set to the value of the followers defined in the cluster view.
Users can switch between async and sync replication at any time without the
need to restart anything.
> *: Handle synchronous replication

- pkg/postgresql/postgresql.go
Also if this is an hack and not the final solution, it was addding access from
all the networks, for all the databases with md5 authentication only for the
replication user and not for all the users.
> postgresql: enable md5 auth for all the users.

- README.md
- doc/syncrepl.md
And in the meantime add a link to the syncrepl.md doc from the main
README.md.
> doc: fix curl command typo.

- cmd/keeper/keeper.go
- pkg/cluster/member.go
- tests/integration/ha_test.go
Get pgstate at timed intervals instead of getting it during every pgState http
handler.
> keeper: run pgstate async from pgStateHandler.

- build
Use static binaries for stolon-sentinel and stolon-proxy since they will be
needed for docker/rkt images.
stolon-keeper cannot be built as a static binary since it needs to know its
current os user and this needs cgo enabled.
Add some notes and a warning to the user for speeding up build using go
install.
> build: create static binaries.

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/clusterview.go
Instead of always computing if keeper is healthy looking at the ErrorStartTime,
do this only in updateKeeperState.
This is useful for:
* get from an external client the keeper health state
* if clusterconfig KeeperFailInterval is lowered at runtime, sentinels won't consider
as healthy keepers already marked as unhealthy.
> cluster: add Healthy field to KeeperState

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- doc/simplecluster.md
- doc/syncrepl.md
- examples/kubernetes/README.md
- pkg/cluster/clusterview.go
- pkg/cluster/config.go
- pkg/cluster/config_test.go
- pkg/etcd/etcd.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
This is preparation work for being able to configure the cluster config.
With this patch the cluster config is managed by the leader sentinel and is
part of the clusterview, so when it's updated the clusterview version will be
increased.
This patch will (temporary) disable the ability to setup synchronous
replication since it's not possible to write the clusterconfig directly to
etcd.
> cluster: make cluster config part of the cluster view.

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/lock/dir.go
- Godeps/_workspace/src/github.com/coreos/rkt/pkg/lock/keylock.go
- cmd/keeper/keeper.go
- tests/integration/init_test.go
- tests/integration/utils.go
To avoid multiple keeper working on the same datadir and concurrently trying to
manage their data and postgres instance.
> keeper: Take an exclusive lock on dataDir.

- scripts/semaphore.sh
This scripts does the setup steps needed for semaphoreci and previously defined
in the semaphoreci ui.
Now the semaphoreci ui has only defined one thread that executes
`./scripts/semaphore.sh`
> semaphoreci: add script for semaphoreci

- scripts/semaphore.sh
- test
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/utils.go
Instead of relying on an already running etcd, start it in the tests.
> tests: start etcd inside tests.

- cmd/proxy/proxy.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
Since multiple proxies can be load balanced, the lb needs to know which proxy
is healthy.
Before this patch on error communicating with etcd or with an empty proxyConf
the proxy closes connections to the previous master but continues accepting
connections and closing them instantly.
With this patch, on error communicating with etcd or with empty proxyConf the
proxy stops listening. It will restart listening on successful etcd
communication and a populated proxyConf.
In this way a load balancer with a standard tcp check will detect the proxy as
not healthy and not balance to it.
This is enabled by default and can be disabled with `--stop-listening=false`
> proxy: stop listening on error or empty proxyConf.

- cmd/proxy/proxy.go
- tests/integration/proxy_test.go
It makes more sense to stop listening only on communication problems with etcd
since it's the unique case when the proxy doesn't know what it should do and
shouldn't be balanced.
Instead having an empty proxyConf and closing the listening socket will exclude
the proxy from a balancer without any reason since its state is good.
> proxy: stop listening only on etcd error

- examples/kubernetes/stolon-proxy.yaml
When the stolon proxy stops listening the readiness probe will detect this and
avoid sending requests to that pod.
> kubernetes: add readiness probe for stolon proxy.

- cmd/keeper/keeper.go
- pkg/postgresql/utils.go
- pkg/postgresql/utils_test.go
Since the keeper's id is used as the postgres replication slot name it needs to
be a valid replication slot name.
From the postgreSQL 9.4 manual: "Each replication slot has a name, which can
contain lower-case letters, numbers, and the underscore character."
> keeper: validate id against postgres repl slot name rules.

- examples/kubernetes/README.md
- examples/kubernetes/stolon-keeper.yaml
- examples/kubernetes/stolon-proxy.yaml
- examples/kubernetes/stolon-sentinel.yaml
These will be changed in a release pointing to the actual released version.
> kubernetes: on master branch use `sorintlab/stolon:master` docker image.

- cmd/keeper/keeper.go
Now they can be configured by the user.
> keeper: remove hardcoded wal archive parameters.

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- pkg/postgresql/postgresql.go
keeper: Since the clusterconfig is needed to instantiate the postgres manager,
loop trying to get it. This is needed since the postgres manager is currently
stateful and needs to be instantiated during the keeper startup (see the TODO
to make it stateless).
sentinel: the clusterconfig is needed at startup only to retrieve the
SleepInterval, if it cannot be retrieved just use the DefaultSleepInterval.
> sentinel/keeper: handle store communication problems on start.

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/config.go
- pkg/cluster/config_test.go
- tests/integration/ha_test.go
- tests/integration/utils.go
When initing a new cluster (with an empty db) it can be useful to be able to
start multiple keepers and let the sentinel randomly choose one as the master
(since they are both empty).
This will avoid the need to start one keeper, start the sentinel(s), wait for
the sentinel to elect the keeper as master, then start the other keeper(s).
To make this useful on startup, there's the need to be able to specify an
initial cluster config, this will come in a future patch.
> Add InitWithMultipleKeepers cluster config option

- tests/integration/utils.go
If the udp port is in use don not return error but continue the loop.
> tests: Fix getFreeTCPUDPPort

- cmd/sentinel/sentinel.go
- tests/integration/init_test.go
- tests/integration/utils.go
Add an `--initial-cluster-config` option to the sentinel to specify a file
containing the clusterconfig to use at cluster initialization.
This option, will be ignored on an already initialized cluster.
This is useful to define a clusterconfig without using `stolonctl config
set/patch` after the cluster is initialized.
It's also useful when there's the need to define the `InitWithMultipleKeepers`
cluster config option at first cluster initialization.
> Add option to provide initial cluster config

- test
- tests/integration/config_test.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
since some integration tests are quite long (minutes), run them in
parallel.
To avoid unreadable logging (due multiple tests running in parallel),
use only the `testing` pkg logging functions so the output will be shown
only on error or at the end of every test (since we pass `-v` to `go
test`).
By default 4 parallel tests will be run. The parallelism level can be
configured with the PARALLEL environment variable when invoking the test
script.
> Run tests in parallel

- scripts/semaphore.sh
Test on both postgreSQL 9.4 and 9.5.
Actually postgreSQL 9.5 is manually installed since it's not available
on semaphore's images.
> Update semaphore scripts to also test on postgres 9.5

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- pkg/postgresql/postgresql.go
- test
- tests/integration/config_test.go
- tests/integration/ha_test.go
Previously when switching an instance from master to standby role, a
full resync was always executed.
Sometimes an old master is on the same branch of the new one and can
become a standby without the need to full resync.
> keeper: resync from master only when needed.

- cmd/keeper/keeper.go
- pkg/postgresql/connstring.go
- pkg/postgresql/postgresql.go
- tests/integration/ha_test.go
When configuring a standby node, use the reported followed node instead
of the master. This is actually the same node but will change when
supporting cascading replication.
Also handle the case when a standby doesn't have to follow any node.
Currently these are transient cases after master election and in future
this can happen when an user will be able to define a maximum number of
standbys.
> keeper: use followed node instead of master

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
Instead of dealing with both connection URL and connection params and
converting between them in some cases, directly use connection params.
> keeper: use connParams instead of connection URL

- README.md
- tests/integration/ha_test.go
- tests/integration/utils.go
Also add a related entry in the README.
In the meantime remove unneeded `\n` in tests logging.
> tests: test changing keeper/postgres addresses.

- README.md
- cmd/keeper/keeper.go
- doc/cluster_config.md
- doc/pg_rewind.md
- pkg/cluster/config.go
- pkg/postgresql/postgresql.go
- tests/integration/ha_test.go
- tests/integration/utils.go
This patch adds pg_rewind support. By default it's disabled and can be
enabled setting the `use_pg_rewind` cluster config options to true.
Since pg_rewind needs to connect to the master instance with a superuser
role, the superuser credential needs to be provided (currently at
startup using environment variables or options (discouraged)) to all the
`stolon-keeper` processes. For security reason they cannot be provided
inside the cluster config.
It'll also work with synchronous replication (pg_rewind needs to connect
with `synchronous_commit` disabled at its session level).
Add related tests.
Add related documentation.
> keeper: add pg_rewind support

- cmd/keeper/keeper.go
- pkg/store/store.go
Instead of writing a persistent discoveryInfo key, use a ttl.
Now there's a dedicated goroutine, fired with a timer, that will update
the discoveryInfo (since the main loop can block for some time on some
operations and updating the discoveryInfo inside it can cause the key to
expire).
> keeper: use ttl for store discovery

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- examples/kubernetes/README.md
- examples/kubernetes/secret.yaml
- examples/kubernetes/stolon-keeper.yaml
- examples/kubernetes/stolon-sentinel.yaml
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
* Adds initial-su-username and initial-su-password-secret-file parameters. If these are set, stolon will set the proper password for the initial superuser when postgresql is first initialized.
* Adds an example secret and usage to the Kubernetes examples.
* Adds support for specifying a namespace to sentinel. This allows stolon to be ran outside of the "default" namespace.
> Setting the initial pgsql superuser password

- cmd/keeper/keeper.go
- doc/cluster_config.md
- doc/pg_rewind.md
- doc/simplecluster.md
- examples/kubernetes/stolon-keeper.yaml
- pkg/cluster/config.go
- pkg/cluster/config_test.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- pkg/util/user.go
- tests/integration/config_test.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/utils.go
This patch tries to unify the user and password management.
* Since the replication username and password are also sensitive, remove
them from the clusterconfig and require the user to provide them as
keeper options. Obviously they need to have the same values for all the
keepers (`--pg-repl-username`, `--pg-repl-password[file]`).
* Use `--pg-su-username` and `pg-su-password[file]` options for all the
superuser required accesses:
* to setup the superuser at db initialization time (previously it was
directly used the os username running the keepers, now it defaults to
this if not specified)
* as credentials used by the keeper for superuser access to the postgres
instance.
* as credentials for pg_rewind.
* The replication and superuser password options can be provided as
parameters …
> keeper: refactor user and password management and options

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- examples/kubernetes/README.md
- examples/kubernetes/stolon-sentinel.yaml
This option will let the user choose the discovery type (store or
kubernetes). By default it'll be detected.
The keeper will always publish its discoveryInfo to the store, it's up
to the sentinel to use it or not.
> stolon: add --discovery-type option.

- cmd/keeper/keeper.go
Restrict the display of the replication password to debug logging level. Keep the rest of the existing log.infof information.
> Restrict display of replication password

- .travis.yml
Add travis CI to just test compilation and unit tests (no integration tests)
with multiple go versions (1.5, 1.6 and 1.7) and architectures (amd64 and
arm64).
> stolon: Add travis CI.

- scripts/semaphore.sh
Now semaphore provides go1.7 so no need to do an external go installation.
> CI: no need for external go anymore

- cmd/keeper/keeper.go
- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- cmd/stolonctl/config_get.go
- pkg/cluster/clusterview.go
- pkg/store/store.go
- tests/integration/init_test.go
- tests/integration/utils.go
This field (now with value 0 to be compatible with the current clusterdata that
doesn't have this field) will be used to be able to do and detect backward
incompatible format changes.
> cluster: Add FormatVersion field to clusterdata.

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
Add a prefix to stolon managed replication slot names so we can filter out
other replication slots.
This can permit an user to add its own replication slots (for example for
external standbys). Before this patch this wasn't possible since the keeper
would have removed them.
> keeper: prefix replication slot names.

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
- tests/integration/utils.go
Always overwrite (instead of appending) pg_hba.conf.
This also removes default entries created by initdb where local users
where trusted.
> postgres: update pg_hba.conf handling

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- pkg/cluster/cluster.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- test
- tests/integration/init_test.go
- tests/integration/pitr_test.go
- tests/integration/utils.go
Don't move previous postgresql.conf but start instance with a temporary
config file.
Save locally init parameters so they can be restored if the keeper is
restarted before the sentinel has moved the cluster status to normal
phase.
Use pg_file_settings when available (pg >= 9.5) to retrieve pg
parameters.
Improve and add tests.
> keeper: improve handling of previous postgresql.conf

- cmd/proxy/proxy.go
- cmd/stolonctl/status.go
- doc/stolonctl.md
- pkg/cluster/member.go
Reporting proxy listen address is not useful since the proxy may listen
on INADDR_ANY.
> proxy: Don't report listen address

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
Two db cluster can be on the same timeline but forked at different
points in previous timelines. pg_rewind doesn't consider this case and
thinks that they are in sync and a rewind isn't needed.
Handle this case checking if, after pg_rewind, the db are not in sync and
launch a full resync.
> keeper: handle pg_rewind wrongly considering dbs as not forked

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- tests/integration/ha_test.go
Keep the failed master role to Master so the keeper will keep
the postgres started and it can be reelected when coming back if the
other standby(s) fails to become master.
Add a test for this case.
> sentinel: make old master re-electable.

- cmd/sentinel/sentinel.go
- pkg/cluster/cluster.go
Saving the keeper and db first error time in the cluster data make this
subscetible to clock skews between sentinels if a new one becomes the
master.
This patch moves the first error time to a sentinel in memory value.
When a new sentinel becomes the master (or the current one is restarted)
the timers are empty so the failure detection time restarts. This isn't
a usually a big problem (just more time to declare a keeper non
healthy).
> cluster: don't save keeper/db first error time

- cmd/sentinel/sentinel.go
- pkg/timer/timer.go
- pkg/timer/timer_fallback.go
- pkg/timer/timer_linux.go
This patch adds monotonic timer support for linux. A monotonic timer is
definitely needed to avoid problems in the elapsed time calculation if
the clock jumps backward/forward due to external changes (by the user or
for any other reason).
We currently just use a clock_gettime syscall instead of the vdso since
we don't have so many calls and the perfomance gap is not noticeable and
the syscall will work on every linux arch.
The Now() method returns an int64 instead of a time.Time since it's not
a wall clock but a time since an unspecified starting point.
The timer pkg also adds a Since utility function to easily calculate
elapsed time.
> *: Use monotonic timer

- cmd/sentinel/sentinel.go
For the moment, since restoring a db con take a very variable time, do
not use a timeout. In future a configurable (perhaps without a default)
timeout could be added.
> sentinel: no pitr timeout

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
- tests/integration/init_test.go
Don't write the postgresql.conf when starting with a temporary config
file.
Reset postgres manager init parameters when initializing.
Add/fix init tests to cover more cases.
> keeper: fix init pg parameters handling

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
Using the db ChangeTime saved in the cluster data to determine if a db
is converged makes the check subscetible to clock skews between
sentinels if a new one becomes the master and when the clock goes
backward/forward for whatever reason.
This patch moves the convergence interval calculation to a sentinel in
memory value.
When a new sentinel becomes the master (or the current one is restarted)
the timers are empty so the convergence detection time restarts. This
isn't a usually a big problem. It may have an impact on big convergence
times (for example during a restore) since there's a greater possibility
that another sentinel becomes the master/is restarted.
> sentinel: don't use registered changetime to get db convergence state.

- cmd/sentinel/sentinel_test.go
Since the semaphore ci linux machine has a monotonic clock starting from
zero when booted, the sentinel tests were sometimes failing not
considering the db as not converged.
Fix this by setting the db convergence timer to a quite big negative
value.
> sentinel: use negative db convergence timer value in tests

- common/common.go
Remove the unneded call to String() that generates strange UIDs.
> common: fix UID() output

- scripts/semaphore.sh
Drop tests with 9.4 to avoid too long test times.
> semaphore: test with postgresql 9.5 and 9.6

- doc/simplecluster.md
- examples/kubernetes/README.md
The logging output has changed in #187. Fix command output reported in
the doc to the new format.
Remove a `--port` option leftover (doesn't exist anymore from #195).
> doc: update for new changes

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- common/common.go
- glide.lock
- glide.yaml
- pkg/cluster/cluster.go
- pkg/cluster/member.go
- tests/integration/config_test.go
- tests/integration/utils.go
- vendor/github.com/sgotti/gexpect/gexpect.go
The keeper at start will generate a bootUUID and, before doing any
operation, will check that the generated bootUID matches the one
registered in the cluster data or will stop/keep stopped the database
instance.
>  keeper: wait for updated keeper state at start.

- tests/integration/config_test.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/pitr_test.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
* setupServer doesn't wait for db being up but just starts all the
keepers.
* getRoles renamed to waitMasterStandbysReady. It now reads the cluster
data waiting for a master being ready.
* Renamed multiple test store related variables and removed unuseful
kvstore creation since it's already provided by the teststore.
> tests: various cleanups

- tests/integration/utils.go
This test needs stop the standby in a moment between electing the
standby as new master and before it reports that promotion
successfully happened.
Try to do this lowering the sleepInterval in the various Wait* utility
functions.
> tests: fix TestFailoverFailed flackiness

- pkg/store/store.go
libkv etcd implementation populates both prevIndex and prevValue to the
v2 api. This is causing problems with big values (since it puts the
prevValue in the PUT url).
This patch removes the KVPair Value before invoking the AtomicPut.
> store: remove prev value before AtomicPut

- cmd/keeper/keeper.go
- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- cmd/stolonctl/init.go
- cmd/stolonctl/spec.go
- cmd/stolonctl/status.go
- cmd/stolonctl/stolonctl.go
- cmd/stolonctl/update.go
- common/tls.go
- examples/kubernetes/stolon-keeper.yaml
- examples/kubernetes/stolon-proxy.yaml
- examples/kubernetes/stolon-sentinel.yaml
- pkg/store/store.go
- tests/integration/utils.go
To enable tls the endpoints should be provided with an https scheme.
Add an option to define the ca file to verify the server certificate.
Add options to set the client cert and key pairs (for client
authentication with etcd)
Add an option to skip server tls cert verification.
> *: enable tls support for store

- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/cluster.go
- tests/integration/ha_test.go
- tests/integration/utils.go
Check if standbys are failed and create new ones.
Use the MaxStandbyPerSender value to determine the max number of
expected good (working) standbys.
Also handle MaxStandbyPerSender changes in the cluster spec.
> sentinel: handle failed standbys replacement

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/cluster.go
- tests/integration/ha_test.go
- tests/integration/utils.go
This patch move the control of db resync from the keeper to the
sentinel.
Now a resync is allowed only during db initialization, so if the
sentinel choose that a db needs a resync it should remove the current db
from the cluster data and define a new db with initMode == resync. The
keeper will resync only when it sees a new db assigned to it and choose
if it makes sense to use pg_rewind or do a full resync.
For this reason the "bad" db detection (branched or different systemID
(this should happen only if a user changes a standby db data out of the
stolon control) is done by the sentinel.
This has other advantages:
* since it's the sentinel detecting bad dbs it can better control
standby removal from the clusterdata and from future proxing.
* the resync db initMode can also be used for …
> stolon: control db resync from the sentinel

- build
The script failed to run on OSx because `readlink -f` is not supported by Darwin system.
> Reproduce readlink -f behavior on osx

- pkg/postgresql/connstring.go
- pkg/postgresql/postgresql.go
Like done for pg_rewind also pg_basebackup should create sessions on the
master with synchronous_commit disabled.
> keeper: disable synchronous_commit for pg_basebackup.

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
The current keeper code is handling only SIGINT for shutdown. If the keeper receives a SIGTERM it shuts down uncleanly. If running inside a Docker container, this means the Postgres process is killed uncleanly as well, which is bad.
This is important because Docker's `docker stop` and Kubernetes' `kubectl delete pod` stop the container by sending SIGTERM. 
This PR: 
- Adds SIGTERM to the handler
- Removes SIGKILL, since it can't be catched.
- Changes SIGINT to use syscall as well, for consistency.
> Handle SIGTERM as well as SIGINT for shutdown.

- examples/docker/Dockerfile-Keeper
Causes a error: Error response from daemon: Syntax error - can't find = in "RUN". Must be of the form: name=value
> Unnecessary escaping newline

- examples/kubernetes/rc/stolon-keeper1.yaml
In 7b2525de287a169c68fd21403236a189df338ce9 we forgot to also fix
rc/stolon-keeper1.yaml
> k8s examples: missing for for rc/stolon-keeper1.yaml

- README.md
- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- pkg/postgresql/utils_test.go
- scripts/semaphore.sh
- tests/integration/pitr_test.go
- tests/integration/utils.go
Add support for postgresql 10 (at least for current beta1).
The changes are minimal:
* Add detection for current pgdata version (also add detection for
binaries version (currently not used))
* Handle different pgdata directories between postgres 9 and 10.
* Use pg_switch_xlog or pg_switch_wal if on 9 or 10 (used only in
integration tests)
Test also postgres10 on semaphore so we'll notice if some breaking
changes are added during postgres10 development.
> *: support postgresql 10

- cmd/sentinel/sentinel.go
- scripts/semaphore.sh
- tests/integration/ha_test.go
- tests/integration/utils.go
Increase tests parallelization to 20.
Free up some disk space to have enough space for parallel test dirs.
Increase SysV ipc semaphores to handle a big number of parallel
postgres instances.
> tests: speedup semaphore tests

- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/pitr_test.go
- tests/integration/standby_test.go
- tests/integration/utils.go
some distribution have a template postgresql.conf used by initdb that
enables some custom logging (for example fedora enables the logging
collector and logging to a file).
For debugging purposes, we want to see the postgres instance logs in the
tests output.
> tests: force postgres logging to stderr

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
running pg_ctl -w means it will wait for a timeout (default 60 seconds)
for the db accepting connection. But after the timeouts pg_ctl returns
an exit code of 0 and the keeper interprets this as the db being ready.
We should instead additonally check if the db is really ready or
error/wait based on the current operation:
* On PITR we should wait for a longer timeout (since restoring wals can
take a long time).
* After a resync with pg_rewind, if the db isn't ready, we assume that
it's probably waiting for some unavailable wals, so we force a full
resync.
In the meantime force the pg_ctl start timeout to 60 seconds (default)
to avoid having this overwritten by a parent PGCTLTIMEOUT environment
variable.
> keeper: check/wait for db ready

- pkg/postgresql/postgresql.go
- tests/integration/ha_test.go
We were emptying the pg_rewind environment since setting cmd.Env != nil
will make os.Exec to use only cmd.Env and not the parent environment. This
caused pg_rewind to fail while trying to find the `initdb` command.
Fix this keeping the parent environment. Only PATH is probably needed but
for the moment just do what is already done when executing pg_ctl
(preserve all the parent environment variables).
In the meantime improve TestTimelineFork to wait a bit more in case of a
successfull pg_rewind but with unavailable wals and add some additional
checks.
> keeper: fix pg_rewind invocation

- cmd/stolonctl/init.go
In the `initCluster()` function there was a log line to `stdout` where we
warn the user that the database data will be overwritten. The word overwritten
was mis-typed as overwrited. This change fixes that.
Signed-off-by: Tim Heckman <t@heckman.io>
> Fix typo in initialization log line

- tests/integration/ha_test.go
- tests/integration/utils.go
sometime some tests timeouts on semaphore (since we are using a lot of
parallel jobs and some processes can become starved on I/O).
> tests: increase some timeouts

- cmd/proxy/proxy.go
- pkg/cluster/cluster.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
the Check function is critical, if it timeouts for whatever reason (i.e
blocked reading/writing to the store, resolving address etc...) the
proxy should drop connections and stop listening.
Since many functions non yet support a Context we use a timeout timer
to handle Check timing out (blocked) or returning an error.
As an additional gain, in this way we can also retry some times until
timeout when we have errors reading from the store while previously we
dropped connections at the first error.
> proxy: handle check timeouts and errors

- cmd/keeper/keeper.go
- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
Do not limit the log level to be only debug or info.
> Added --log-level argument

- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- cmd/sentinel/sentinel_test.go
- pkg/cluster/cluster.go
- pkg/cluster/member.go
- tests/integration/ha_test.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
This patch waits for proxies to report that they closed connections to
an unelected master before enabling connections to the new one.
This tries to avoid a small windows where a proxy can send data to
an unelected master when a new master is already active and other
proxies are already sending connection to it causing some transactions to
go to the right master while other to the old one since the proxy hasn't
yet read from the store to close its connections.
This could happen only when the failover is faster than the proxy
timeout and this isn't usually the case.
This is done reading the proxyInfo reported by the proxy to check if
they are at the right proxy generation.
If a proxy isn't reporting its proxyInfo (problems
talking to the store, partitioned etc...) the proxyInfo will expire …
> sentinel: wait for proxies closing connections

- build
- scripts/semaphore.sh
- test
Same approach as is common for python.
Fixes builds on NixOS and other environments that guarantee
reproducible builds.
> scripts: Use `/usr/bin/env bash` instead of `/bin/bash`.

- cmd/keeper/keeper.go
if initialization failed for whatever error we can have the instance
active. So try to stop it before cleaning instance data.
> keeper: retry instance stop if initialization failed

- cmd/keeper/keeper.go
- cmd/sentinel/sentinel.go
- pkg/cluster/cluster.go
- pkg/cluster/member.go
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- pkg/postgresql/utils_test.go
- tests/integration/ha_test.go
- tests/integration/pitr_test.go
- tests/integration/utils.go
This patch detects if a standby won't be able to sync with master due to
missing wals.
Also if using replication slots this may happen since replication slots
are created only on the master so if a standby is down and a new
standby is elected as master it may not have all the wals needed by the
other standbys.
Since looks like the unique way to see if an instance cannot sync is to
parse logs for lines like:
FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000010000000000000004 has already been removed
and parsing postgres logs will be error prone, we use another approach:
* Make the keepers report the older log files available in the
pg_xlog/pg_wal dir
* if a standby isn't syncing check if the required wal file name
is older than the older one available on …
> *: detect if standby can't sync due to missing wals

- pkg/postgresql/utils.go
If some pg_parameters that cannot be changed without a restart
are removed from the postgresql.conf file the view will contain some
rows with null name and setting and the error field set to the cause.
So we have to filter out these or the Scan will fail.
> postgres: filter out null parameters in pg_file_settings view.

- pkg/cluster/cluster.go
maxStandbyLage => maxStandbyLag
> cluster: fix typo in maxStandbyLag json field name

- cmd/keeper/keeper.go
- common/common.go
- pkg/postgresql/postgresql.go
- tests/integration/ha_test.go
* The default pg_hba entries for local normal and replication
connections are stricter and the minimal required for keepers
connections.
This is the initial work for supporting custom pg_hba entries.
> keeper: use unix domain socket for keeper postgres connection.

- cmd/keeper/keeper.go
If dropping the replication slot fails (usually if the standby is still
connected) log the error but continue so we can mark the keeper as
converged to the new generation anyway.
> keeper: log but ignore errors on dropping repl slots.

- pkg/postgresql/postgresql.go
Also fetch wals when calling pg_basebackup. We could also stream them but this
will require an additional connection and wal sender so for now, since we are
using replication slots, just rely on fetching at the end of the basebackup.
This will fix pg_basebackup waiting indefinetly if archive mode is enabled but
the archive command on the primary isn't working correctly.
> postgres: also fetch wals during pg_basebackup

- cmd/keeper/keeper.go
- doc/architecture.md
- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
> Added auth method for su/replication user

- tests/integration/ha_test.go
- tests/integration/utils.go
avoid wasting too much disk space doing less wal switches and cleaning unneeded
wals (using low values for min_wal_size and max_wal_size).
> tests: lower TestStandbyCantSync disk usage

- README.md
* clarify that also etcd3 is supported (also if >= 2.0 was already clear enough)
* clarify supported and tested OSes and Go versions.
> README: improve runtime and build requirements descriptions

- cmd/keeper/keeper.go
- pkg/cluster/cluster.go
- pkg/postgresql/postgresql.go
Unfortunately pg_ctl start changed behavior in postgresql 10:
pg_ctl for postgres < 10 with -w will returns 0 also if the instance isn't ready
to accept connections.
While in postgres >= 10 it will return a non 0 exit code (1 like when the
instance fails to start) making it impossible to distinguish between problems
starting an instance (i.e. wrong parameters) or an instance started but not
ready to accept connections.
To work with all the versions and since we want to distinguish between a failed
start and a started but not ready instance we are forced to not use pg_ctl and
write part of its logic here (I hate to do this).
Now PGManager.start method directly starts the instance using the "postgres"
executable and waits 1 minute to see if the process starts (checking its pid file)
or …
> keeper: improve db start logic

- cmd/keeper/keeper.go
lockFile wasn't referenced and so the gc will collect it and close its
file descriptor releasing the lock.
To keep it referenced just explicitly Close lockFile before exiting.
> keeper: fix datadir locking

- doc/postgres_parameters.md
- pkg/postgresql/postgresql.go
- tests/integration/config_test.go
Since postgresql.auto.conf overrides postgresql.conf parameters,
changing some of them with ALTER SYSTEM could break the cluster
(parameters managed by stolon could be overridden) and make pg
parameters different between the instances.
ALTER SYSTEM writes to postgresql.auto.conf, so we make it a symlink
to /dev/null. An ALTER SYSTEM command will return an error.
> keeper: disable ALTER SYSTEM commands.

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
When restoring with PITR (at least with WAL-E), stolon-keeper do not wait until full recovery before marking itself as initialized.
This allow for read-only connection on a database that is still recovering and thus allow client to see outdated content.
Step to reproduce:
* Configure a cluster with WAL-E backup
* Create a custom table, insert data
* Generate WAL, using pgbench for example
* Update data from custom table
* Trigger a PITR recovery. To help seeing the issue, adding a sleep in the restoreCommand may help
* During the recovery, once Postgres reach consistent state, stolon will accept connection. Querying the custom table will allow to see initial inserted data.
I've made this an option because I'm not sure if it was intended or not to allow read-only connection during the …
> Add waitFullRecovery option to PITR

- pkg/postgresql/postgresql.go
- pkg/postgresql/utils.go
- tests/integration/ha_test.go
- tests/integration/proxy_test.go
- tests/integration/utils.go
Remove sleep and instead, in WaitClusterSyncedXLogPos, check that the reported
ones are greater or equal a provided XLogPos.
In the various tests get the primary (for standby cluster) or master XLogPos and
use it in the call to WaitClusterSyncedXLogPos.
In TestTimelineFork wait for standbys to have reported their xlogpos just before
stopping them.
> test: improve wait for reported xlogpos

- cmd/common.go
- cmd/keeper/keeper.go
- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- cmd/stolonctl/stolonctl.go
- common/common.go
- doc/architecture.md
- pkg/store/store.go
- tests/integration/config_test.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/pitr_test.go
- tests/integration/proxy_test.go
- tests/integration/standby_test.go
Add a `--store-prefix` option to specify the store prefix.
In the meantime, for consistency, rename StoreBasePath to StorePrefix.
> *: Make the store prefix configurable

- tests/integration/ha_test.go
Get the standby[0] db uid before stopping it or we can end up reading the new db
uid if the sentinel was faster than us replacing the old db uid.
> test: TestStandbyCantSync move db uid before stop

- cmd/keeper/keeper.go
When we start an instance during the main logic we should wait that
it's ready (or the next command to update its replication slots will fail).
> keeper: add some missing waits for instance ready

- cmd/proxy/proxy.go
- cmd/sentinel/sentinel.go
- cmd/stolonctl/status.go
- pkg/cluster/member.go
- pkg/store/store.go
- tests/integration/sentinel_test.go
- tests/integration/utils.go
Don't rely on proxyInfos being expired by the store but handle this at the
sentinel level. Like already done for the keepers check that the published
proxyInfo is updated by checking that the published InfoUID is changed or ignore
it if it's not updated for a specified time interval (assuming that the proxy
stopped listening in this interval).
This is also needed for future kubernetes based store where the proxyInfos is
read from the pod and under some error conditions it won't expire but just not
being updated.
Also improve the proxy spec update logic in updateCluster to only check for
converged proxies when a new master is elected (the proxies spec master is
empty)
> sentinel: handle stale proxyInfos

- build
When using source tarball, builds fail when discovering current version. This change allows for STOLON_VERSION, if set in the environment, to be used as the build version instead of attempting discovery.
The original issue was identified when building v0.8.0 RPMs. See [source](https://github.com/abn/stolon-rpm) for current workaround.
> build: allow explicit version configuration

- cmd/sentinel/sentinel.go
if the keeper hasn't reported the systemid ignore it and skip the validity check.
> sentinel: ignore empty systemid

- cmd/keeper/keeper.go
- pkg/postgresql/postgresql.go
Just check if instance is started when needed without the need to kee the variable
updated at every operation.
> keeper: remove "started" variable

- test
With go 1.10 integration tests will returns cached results since no test
code has changed.
Disable caching using the `-count 1` option.
> tests: disable caching in integration tests

- cmd/keeper/cmd/keeper.go
If the sentinel removes a db from the clusterdata, the related keeper should
stop the instance (currently we keep the data).
> keeper: stop running instance when db not assigned.

- cmd/sentinel/cmd/sentinel.go
- cmd/sentinel/cmd/sentinel_test.go
- pkg/util/slice.go
* Update the sync standbys only if the reported ones are the same as the required
ones. In this way, when we have to choose a new master we are sure that there're
no intermediate changes between the reported standbys and the required ones.
* When we have to choose a new sync standby as master we can just choose one of
the common standbys between the reported and the required one since we are sure
these are defined in the master as sync standbys
* Improve logic to always have some real sync standbys up to
MinSynchronousStanbys, also if not in good state, to improve the possibility
to be able to choose a sync standby to replace a failed master.
* Always keep a common standby between the previous and the wanted
synchronousStandbys
> sentinel: improve sync standby management logic

- cmd/keeper/cmd/keeper.go
- doc/postgres_parameters.md
- pkg/postgresql/utils.go
- pkg/postgresql/utils_test.go
- tests/integration/config_test.go
* Read the user provided pgParameters and if the provided wal_level is "logical"
use it, other values (invalid or unsupported) will return the default stolon wal_level.
* Also if hot_standby is valid for every supported version let's prefer
"replica" when using postgres >= 9.6
> keeper: improve wal_level selection

- pkg/store/k8s.go
The event recorder namespace was set to `default` instead of using the right one.
> k8s store: fix wrong namespace used for election events

- scripts/semaphore-k8s.sh
v0.26.0 with vm driver set to none doesn't work on semaphore vm since they don't
use systemd.
> tests: set minikube version to v0.25.2

- CHANGELOG.md
- doc/architecture.md
- examples/kubernetes/stolon-keeper.yaml
- examples/kubernetes/stolon-proxy-service.yaml
- examples/kubernetes/stolon-proxy.yaml
- examples/kubernetes/stolon-sentinel.yaml
- pkg/store/k8s.go
Use `component` label instead off `app` label to filter pods.
The `app` label is usually used to reflect the entire app (for example see
helm label best practices:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md)
Fixes #466 
/cc @Flowkap @lwolf
> k8s store: use component label instead of app

- pkg/postgresql/postgresql.go
pg_rewind isn't happy if the postgresql.auto.conf on the target instance is a
symlink to /dev/null. So remove it before calling pg_rewind.
Fixes #468 
/cc @deepdivenow
> keeper: remove postgresql.auto.conf before pg_rewind

- examples/kubernetes/role.yaml
Resolves a permission error that occurs on sentinel startup.
> add missing resource type

- scripts/semaphore.sh
Lately semaphore VMs are slower than usual and can't support 20 parallel tests.
This patch lowers the parallel tests number to 10.
> tests: lower parallel build on semaphore

- cmd/sentinel/cmd/sentinel.go
- cmd/sentinel/cmd/sentinel_test.go
- pkg/util/slice.go
- pkg/util/slice_test.go
When electing a new master we are swapping the new master uid with the old
master uid in the syncstandbys slice. This could end with an unordered slice in
the spec that will make the sentinel fail the check that the reported standbys
are the same of the spec one blocking any future syncstandby update.
Since the reported order is not a problem just check that the syncstandbys are
the same regardless of their order.
We'll keep the sorting to avoid unneeded updates to synchronous_standby_names by
the keeper.
> sentinel: fix check for same reported vs spec sync standbys

- cmd/keeper/cmd/keeper.go
- common/common.go
- pkg/postgresql/postgresql.go
The current atomic write functions inside pkg/postgresql are missing some error
checks and don't close the file before renaming. Improve common.WriteFileAtomic
to be able to stream writes and use it.
> keeper: fix atomix writes.

- cmd/keeper/cmd/keeper.go
- doc/ssl.md
Set sslmode to `prefer` so, if the user has enabled ssl/tls, it'll also be used for
replication (and pg_rewind).
Now it's not possible to force other options like verify-ca or verify-full since
they requires more effort on the user side and need to be carefully tested.
> keeper: don't disable ssl for replication

- examples/kubernetes/secret.yaml
The example secret is encoded with a carriage return which causes problems with cluster auth when using the default example scripts. Although this password should be changed, users who want to quickly test out stolon in minikube will find that they are unable to authenticate into the cluster using password1.
Referring to #500
> Removing carriage return from example secret

- cmd/keeper/cmd/keeper.go
- tests/integration/ha_test.go
if the local dbuid is different than the clusterdata required one but initmode
is none something bad happened to the local keeper data. This should happen only
when the local dbstate file disappeared (ephemeral data dir, manual remove). In
such case don't just update it with the clusterdata one and continue but report an
error and stop.
> keeper: report error when local dbuid is not correct

- cmd/keeper/cmd/keeper.go
- cmd/sentinel/cmd/sentinel.go
- cmd/sentinel/cmd/sentinel_test.go
- internal/cluster/cluster.go
- internal/postgresql/postgresql.go
- internal/postgresql/utils.go
- internal/util/slice.go
- internal/util/slice_test.go
When using syncrepl don't consider a standby in sync only because it has been
added in the synchronous_standby_names parameter but only when the postgres
instance reports it as in sync (querying pg_stat_replication).
> *: syncrepl, consider only really in sync standbys

- doc/faq.md
Currently links points to doc/doc/architecture.md
> Fix FAQ link to architecture.md

- cmd/keeper/cmd/keeper.go
- cmd/keeper/cmd/keeper_test.go
Hello, 
I was deploying our stolon cluster when I spotted an issue with SUReplAccessStrict mode, 
The hba generated get the master listen address instead of the standby address.
This should work as expected with this fix.
> fixed listen address in SUReplAccessStrict

- scripts/semaphore.sh
Now that postgres 11 beta1 is out let's test also on it.
> tests: test also postgres 11 on semaphore

- test
Temporarily disable gofmt on CI since it'll break when we'll use go 1.10 and go
1.11.
A possible solution could be to check against only one (usually the latest
stable) go version gofmt output (for example gofmt in go 1.10 and 1.11 will
format differently) or check that at least one passes.
> test: temporarily disable gofmt on CI

- internal/postgresql/postgresql.go
- internal/postgresql/utils.go
Consider db as standby is it's in recovery (recovery.conf file exists).
> postgres: simplify standby role detection

- cmd/keeper/cmd/keeper.go
- internal/postgresql/connstring.go
- internal/postgresql/postgresql.go
* Let the postgresql manager create the recovery.conf on start/restart/reload
* Define recovery.conf parameter using the SetRecoveryParameter method and
retrieve them with the RecoveryParameter method
* Simplify the logic to detect when the standby db needs to be restarted due
to changed recovery parameters since we can just compare the current and the
wanted ones.
> keeper: let postgresql manager also manage recovery.conf

- cmd/keeper/cmd/keeper.go
- internal/cluster/cluster.go
- tests/integration/pitr_test.go
* Set recovery_target_action to "promote" when using recovery target settings
* When the user specifies some recovery target settings then accept them only
when the cluster role is not standby (it doesn't makes sense to restore a
standby cluster to a different timeline or stopping at a specified time/lsn/xid)
> *: set recovery_target_action to promote when using recovery target settings

- .gitignore
- .travis.yml
- build
- scripts/semaphore-k8s.sh
- scripts/semaphore.sh
- test
* use go 1.10.x and 1.11.x on travis
* Remove the build hack that uses a local GOPATH:
* Use `go_import_path` on travis and create a symlink to the main org repo on
semaphore
* Users forking stolon repo on github should just use git remotes in the main
repo clone
* Remove messages to build a cgo enabled stdlib, go build cache introduced in go
1.10 also caches this.
* Always use `go build` instead of `go install` so we can directly place
binaries in the project bin dir and choose the binary name
> *: update go version to go1.11 and simplify build

- test
readlink -f option is not available in osx,
instead use greadlink package which is GNU readlink for osx if available
Homebrew provide a coreutils package containing greadlink (GNU readlink)
> Use readlinkdashf function in test for cross compatibility with osx

- cmd/keeper/cmd/keeper.go
- tests/integration/init_test.go
Remove trailing new lines (trailing line feed and carriage return chars) like
already done by initdb and libpq when reading a password file.
> keeper: remove trailing new lines from passwords

- cmd/keeper/cmd/keeper.go
- cmd/keeper/cmd/keeper_test.go
This avoids unneeded reloads between checks due to changed addresses order.
Fixes #556
> keeper: sort keepers addresses in pg_hba.conf

- build
- scripts/gen_commands_doc.sh
- scripts/readlinkdashf.sh
- test
Tasks:
1. Moved `readlinkdashf` function in `build`, `test` to common file `readlinkdashf.sh`
2. Using `readlinkdashf.sh` file in `gen_commands_doc.sh` to generate docs in mac.
> Make readlink work in osx for gen_commands_doc.sh

- internal/postgresql/utils.go
Now that golang sql.db and libpq support context in exec and query functions for
some time, use them.
Will possibly fix a connection leak when ctx expires since the current
implementation doesn't close sql rows on context expire.
> postgres: use sql db context functions

- cmd/common.go
- cmd/keeper/cmd/keeper.go
- cmd/keeper/cmd/metrics.go
- internal/common/common.go
Add a collection of Prometheus metrics to the keeper. The metrics are
aimed to expose errors in the keeper sync loop, providing enough
visibility to detect when the sync is failing (and some insight into
why).
---
Hey stolon maintainers! I want to make this as easy as possible to review, so I'm going to try and write everything you need up-front here. If you have any questions just drop a comment and I'll do my best to answer them.
We're currently moving our Postgres cluster to use stolon, and in doing so we've adapted some tooling we already had to enable zero-downtime planned failover. The tool that allows this is called [stolon-pgbouncer](https://github.com/gocardless/stolon-pgbouncer) which explains its purpose and aims in the readme.
stolon-pgbouncer has native Prometheus metrics and …
> keeper Prometheus metrics

- cmd/keeper/cmd/keeper.go
I have encountered the problem on test mini installation (cluster based on raspberry pi) that autofailover didn't performed after disk (SD card, in case of raspberry) manual insulation.
The problem lies in `PostgresKeeper.updatePGState` routine (cmd/keeper/cmd/keeper.go:561) that Postgres state isn't updated in DCS (consul or etcd) when `PostgresKeeper.GetPGState` routine returns some not null error. Such error is emitted after check whether PGDATA is initialized (`Manager.IsInitialized` routine, cmd/keeper/cmd/keeper.go:641) what is induced after disk file system operation failure (my case).
The current pull request fixes this issue.
> Fix failover process after disk crash

- cmd/keeper/cmd/metrics.go
- cmd/sentinel/cmd/metrics.go
- cmd/sentinel/cmd/sentinel.go
These metrics provide the ability to build alerts that tell us whether the sentinels are operating as expected:
- The last time that the sentinel successfully processed the clusterdata.
- Whether the sentinel is a leader.
- The number of times that the sentinel has been elected leader.
---
This follows on from the keeper metrics in #639.
We've found these sentinel metrics to be extremely useful, upon discovering that our sentinels could occasionally all become stuck - and no decisions would be made across the cluster - when there are issues communicating with etcd (we're planning to upstream a patch for that issue in the near future!)
> sentinel: Add Prometheus metrics

- internal/postgresql/utils.go
If we are having special characters in su username like below
```bash
./stolon-keeper --pg-su-username=user-name # other flags
```
We are getting below error
```
INFO    postgresql/postgresql.go:534    setting superuser password
2019-06-01 01:34:40.031 IST [60923] ERROR:  syntax error at or near "-" at character 14
```
But in postgres, having role as `user-name` is allowed. So it is better if stolon also allow this.
I just added double quotes for `username` in `alter role` command.
> There are two more places in `stolon` where we are altering role. In those two places we are already using double quotes. https://github.com/sorintlab/stolon/blob/master/internal/postgresql/utils.go#L104 and https://github.com/sorintlab/stolon/blob/master/internal/postgresql/utils.go#L115
> Allow special characters in pg-su-username

- cmd/sentinel/cmd/sentinel.go
- cmd/sentinel/cmd/sentinel_test.go
Hi @sgotti,
I was going through the code base to better understand the stolon. I came across `one dead code` in **Sentinel.go**. 
To verify that 
- First, I wrote unit tests for that method (first commit in this PR)
- Second, I removed that dead code and checked. All the tests are passing (second commit)
Please lemme know if I missed any test cases.
> Small dead code removal in Sentinel.go

- cmd/common.go
Adding timeout for `kubeclient` by adding timeout for `restclient`
I have made two commits
- Move common logic into a method called `getKubeValues`
- Added timeout for kubecfg
> Note: I have tested the kubecfg by providing different timeout value and it works.
> Add Timeout for kubeclient

- cmd/keeper/cmd/keeper.go
- internal/postgresql/postgresql.go
Remove capital first letter and use zap.Error to wrap errors
> keeper: fix some logging

- cmd/keeper/cmd/keeper.go
- tests/integration/config_test.go
use the value provided in the pg parameters to set the instance
wal_keep_segments value.
The value is ignored if it's a bad value or lesser than the default value (8).
> keeper: configurable wal_keep_segments

- cmd/common.go
- cmd/keeper/cmd/keeper.go
- cmd/proxy/cmd/proxy.go
- cmd/sentinel/cmd/sentinel.go
[^1]: https://github.com/gocardless/stolon-pgbouncer/pull/46
The stolon_cluster_identifier metric is universal to all stolon
components, and can be used to join metric series across a stolon
cluster. By adding the component label, it's possible to write
polymorphic alerts that expose the component name when firing.
This change also registers the metric in the sentinel and proxy, as it
should be present in all long-lived binaries. This accompanies a change
in stolon-pgbouncer to do the same[^1].
> Label cluster identifier with component

- cmd/sentinel/cmd/sentinel.go
- internal/store/etcdv3.go
- internal/store/store.go
This change fixes an issue we were seeing where our sentinels would occasionally freeze, not responding to etcd changes or making any decisions. This could only be resolved by restarting them all.
We tracked this down to an issue with how the sentinels use etcd elections to determine the leader. An error interacting with etcd can lead to old election keys hanging around, blocking any future elections from completing. The end result is that the sentinels are unable to elect a leader and cannot make any progress.
There's more detail on the specifics of this problem in the commit message, which I'll reproduce here:
> If etcd returned an error, our previous behaviour would be to report the
error and restart an election. The outer loop never responded to the
error by stopping the election, …
> Fix hanging sentinels

- cmd/stolonctl/cmd/init.go
This fixes what is debatably a bug, where supplying the file flag to
`stolonctl init` with a value that points to an empty file results in
initialising the cluster with an `initMode` of `new`.
This behaviour is dangerous because if the user intended to supply a
file that contained a cluster specification with an `initMode` of
`existing`, but mistakenly supplied a path to an empty file, then it
would result in the keeper data being removed.
To resolve this, change the behaviour of the command to always attempt
the unmarshalling of the supplied cluster spec JSON, which will result
in a fatal error in the case of an empty file.
If the user intends to initialise the cluster with a blank (`initMode:
new`) cluster specification then they should do so by omitting the file
flag and cluster …
> Prevent stolonctl init with empty file

- cmd/keeper/cmd/keeper.go
pg_rewind does not support executing against standby nodes. While stolon
doesn't yet support cascading replication, it will never be correct to
run pg_rewind against any node other than the primary.
By making this change now, we future proof stolon and enable any forks
(such as gocardless/stolon) to configure a cascading replication setup
without issue.
> Only pg_rewind against master DBs

- .agola/config.jsonnet
- build
- test
Implement initial run definition for agola CI/CD. It'll use the latest two go
versions (currently 1.12 and 1.13)
Add a test matrix for all the supported postgres version and stores (for etcdv2
and consul just test with the latest postgres version)
In future will add automatic docker example image build and push
> Use agola CI/CD

- examples/kubernetes/stolon-keeper.yaml
- examples/kubernetes/stolon-proxy.yaml
- examples/kubernetes/stolon-sentinel.yaml
new k8s version use `apiVersion: apps/v1` and don't support `apiVersion:
extensions/v1beta1` anymore. They also require a selector to matching the
managed pods.
> k8s example: update deployment api

- .agola/config.jsonnet
- scripts/agola-k8s.sh
* Use bsycorp/kind image to start an already setup k8s cluster inside a
container. We aren't using kubernetes-sigs/kind because it will create a k8s in
docker in docker (two layers) that will take time to setup and won't work inside
a k8s pod without special mounting of host cgroups (due to systemd issues)
* Build the stolon image and push it to the kind cluster internal image store.
* Deploy stolon on k8s using the example deployment
> agola ci: add k8s tests

- .agola/config.jsonnet
- cmd/keeper/cmd/keeper.go
- internal/postgresql/postgresql.go
- internal/postgresql/utils.go
- test
- tests/integration/pitr_test.go
- tests/integration/utils.go
PostgreSQL 12 changed how it manages recovery and standby:
* The "recovery.conf" file has been removed.
* Recovery parameters now live in "postgresql.conf"
* "standby_mode" recovery parameter has been removed.
* Two "signal" files ("recovery.signal" and "standby.signal") are used to define
the recovery mode (instead of using a "recovery.conf" file + "standby_mode" parameter)
Resolves #709
> *: add support for PostgreSQL 12

- cmd/keeper/cmd/keeper.go
- cmd/keeper/cmd/keeper_test.go
- cmd/sentinel/cmd/sentinel.go
"github.com/sorintlab/stolon/internal/postgresql" was imported and used two
times with different names.
Also unify the package name in other files using this package.
> keeper: remove duplicate package import

- cmd/stolonctl/cmd/spec.go
* show only changed options and omit all the empty/null options
* when using --defaults show ALL the options
Do this by using two copies of the clusterspec struct, one with all json tags
with omitempty and one without omitempty that will be casted from the original
cluster spec (so we will get an error when we forgot to updated them when
changing the ClusterSpec struct)
> stolonctl spec: don't show some null clusterspec options

- examples/kubernetes/README.md
Querying service for its IP to connect to the database is too tedious and not needed when we can query directly with service name.
> Use service name instead of querying the service to get its IP to connect to the DB

- go.mod
- go.sum
- internal/store/k8s.go
Use k8s client patch method to update pod annotations (in some versions
replacing the whole pod object will return an error)
> k8s store: patch pod annotations

- cmd/keeper/cmd/keeper.go
- cmd/sentinel/cmd/sentinel.go
- cmd/sentinel/cmd/sentinel_test.go
- go.mod
- internal/cluster/cluster.go
- internal/cluster/member.go
Implements the proposal https://github.com/sorintlab/stolon/issues/696
> Keepers that never become master/sync replica

- internal/store/kvbacked.go
Add dial timeout and keep alive timeout to the etcdv3 client configuration or
under some network problems (not tcp reset from server) the client will never
try other etcd endpoints.
> store: add etcdv3 timeouts

- cmd/keeper/cmd/keeper.go
If the spec required db role is master then unset the current recovery options
since they could be set by the pitr recovery phase.
> keeper: always unset recovery options when wanted role is master

- .agola/config.jsonnet
- cmd/keeper/cmd/keeper.go
- tests/integration/config_test.go
* Handle wal_keep_segments removed and replaced by wal_keep_size
* CI: Remove build/tests/images for upstream unsupported versions (9.4 and 9.5)
> *: add support for PostgreSQL 13

- go.mod
- go.sum
- internal/common/common.go
- tests/integration/config_test.go
- tests/integration/ha_test.go
- tests/integration/init_test.go
- tests/integration/pitr_test.go
- tests/integration/proxy_test.go
- tests/integration/sentinel_test.go
- tests/integration/standby_test.go
- tests/integration/utils.go
Replace the github.com/satori/go.uuid package with the github.com/google/uuid
package to work around the GO-2020-0018 vulnerability.
The vulnerability is fixed in https://github.com/satori/go.uuid/pull/75,
but a release has never been tagged.
> Switch uuid package to get around GO-2020-0018

- .agola/config.jsonnet
- README.md
Now that [Postgres 15](https://www.postgresql.org/docs/15/release-15.html) is out, it will be good to support it.
> *: add support for PostgreSQL 15
