sorintlab/stolon

cmd/keeper/keeper.go, cmd/sentinel/sentinel.go, cmd/sentinel/sentinel_test.go, pkg/postgresql/postgresql.go, test, tests/integration/ha_test.go, tests/integration/init_test.go, tests/integration/utils.go
Also add gofmt and go tool vet checks.
=> sentinel: Add initial updateClusterView tests.

cmd/keeper/keeper.go, cmd/proxy/proxy.go, cmd/sentinel/sentinel.go, pkg/cluster/config.go, pkg/cluster/config_test.go
Add json parsing and validation for cluster config and related tests.
In the meantime rename some fields, remove unused EtcdRequestTimeout and add
config fields descriptions.
=> cluster: Initial json parsing and validation for cluster config.

pkg/postgresql/postgresql.go
Instead of overriding options using postgresql -c argument, just generate the
postgresql.conf file.
The base file created by initdb is renamed and included at the start of the
generated postgresql.conf.
Additionally the config file are firstly created as temporary file, then
atomically moved.
=> postgresql: generate postgresql.conf file instead of using start arguments.

cmd/keeper/keeper.go, pkg/postgresql/postgresql.go
Do not make postgresql Manager change/define the server's parameters and
connection strings, but pass them to it.
=> postgresql: configure all the parameters externally.

examples/kubernetes/README.md
Add all the steps needed to completely test a stolon cluster inside
kubernetes.
=> examples: improve kubernetes example doc.

cmd/keeper/keeper.go
make
* max_replication_slots = MaxStandbysPerSender
* max_wal_senders = MaxStandbysPerSender + 2
Usually two additional wal senders over the ones needed by the standbys are
needed (one for the pgstatus handler and one for the keeper checks).
This assumes no additional processes are connecting to the wal senders or this
will create some problems.
=> keeper: calculate max_replication_slots and max_wal_senders

cmd/keeper/keeper.go
This avoids using an additional used wal if the pg.GetPGstate() functions is
called in parallel with the pgState checker.
The pgStateChecker method has been renamed to updatePGState.
In the keeper loop, we must have an updated pgState, so we call updatePGState
when needed.
=> keeper: use and update lastPGState in keeper loop.

cmd/keeper/keeper.go, cmd/sentinel/sentinel.go, examples/kubernetes/image/docker/Dockerfile, pkg/cluster/clusterview.go, pkg/cluster/config.go, pkg/cluster/config_test.go, tests/integration/ha_test.go
Add an additional NilConfig struct where all the fields are pointers. In this
way when unmarshalling the unprovided fields will be a nil pointer.
In this way will can distinguish between a field with a zero type value or an
unspecified value and correctly merge default values.
=> config: make config handle non specified fields.

cmd/keeper/keeper.go, cmd/sentinel/sentinel.go, pkg/cluster/clusterview.go, pkg/cluster/member.go, pkg/etcd/etcd.go
Rework etcd hierarchy changing and adding new paths for future work on
publishing sentinels and proxies information.
=> etcd: rework etcd hierarchy.

README.md, build, cmd/stolonctl/config.go, cmd/stolonctl/config_get.go, cmd/stolonctl/config_patch.go, cmd/stolonctl/config_replace.go, cmd/stolonctl/listclusters.go, cmd/stolonctl/status.go, cmd/stolonctl/stolonctl.go, doc/cluster_config.md, doc/stolonctl.md, doc/syncrepl.md, pkg/cluster/config.go, pkg/etcd/etcd.go, pkg/etcd/utils.go
* list-clusters
* status
* config get
* config replace
* config patch
=>  stolonctl: Add initial implementation of a stolon client

cmd/keeper/keeper.go, doc/cluster_config.md, doc/postgres_parameters.md, pkg/cluster/config.go, pkg/cluster/config_test.go, pkg/postgresql/postgresql.go, tests/integration/config_test.go, tests/integration/ha_test.go
Users can define global postgres parameters inside the cluster config.
=> cluster: handle cluster config centralized postgres server parameters

cmd/keeper/keeper.go, cmd/proxy/proxy.go, cmd/sentinel/sentinel.go, pkg/postgresql/postgresql.go, pkg/postgresql/utils.go, scripts/semaphore.sh
Fix some new go vet 1.6 reported shadowing errors.
=> Update to go 1.6

cmd/keeper/keeper.go
the current defer logic is wrong since, on error retrieving current
pgState, the lastPGState is rewritten with an empty o partially
populated struct.
Change it to update lastPGState only on success.
=> keeper: correctly set lastPGState

pkg/postgresql/postgresql.go
Remove the datadir if there's an error during database initialization.
So we don't have an unmanagable half initialized database.
=> Postgres: remove datadir on initialization error

cmd/keeper/keeper.go
Instead of copying provided configuration inside keeper variables.
=> keeper directly use config

cmd/keeper/keeper.go
Do not use last known pgstate but get the current pgState (or error if
something fails).
=> keeper: get current pg state for timeline checks.

pkg/cluster/config.go, pkg/cluster/config_test.go
Config.Copy has to copy the PGParameters map.
Also add tests to Config and NilConfig Copy.
=> config: Fix Config.Copy and add Copy tests.

cmd/keeper/keeper.go
In the case two databases have the same timeline but a different switchpoint
then they should be considered forked too.
=> keeper: check for same timeline but different switchpoints.

pkg/postgresql/postgresql.go, pkg/postgresql/utils.go
Check existence of different files/directories. Db is considered initialized if
all of them exists.
=> postgres: improve IsInitialized checks.

cmd/keeper/keeper.go, pkg/cluster/member.go, pkg/postgresql/postgresql.go, pkg/postgresql/utils.go, pkg/postgresql/utils_test.go
This patch makes pkg/postgres more consistent not depending on pkg/cluster
structs.
=> postgres: do not depend on pkg/cluster

tests/integration/utils.go
Use an increasing port counter with a range between 2048 and 16384
(should be below /proc/sys/net/ipv4/ip_local_port_range values to avoid
using ephemeral ports).
This should limit flacky tests caused by port collisions.
=> tests: better free port selection.

cmd/stolonctl/status.go
Fix output when master is not defined and when the db address is not
already known.
=> stolonctl: fix status output

pkg/store/store.go
We were (erroneously) relying on parsing a schemeless endpoint (like
127.0.0.1:2379) and checking that its scheme was empty.
With go 1.8 parsing such endpoints returns an error (introduced in
https://github.com/golang/go/commit/c5ccbdd22bdbdc43d541b7e7d4ed66ceb559030e).
Fix this manually checking that the endpoint starts with a scheme or
assume it's a schemeless endpoint.
In future it'll be better just accept only schemeful endpoints.
=> store: fix handling of schemeless endpoints

cmd/keeper/keeper.go, cmd/proxy/proxy.go, cmd/sentinel/sentinel.go, cmd/sentinel/sentinel_test.go, doc/simplecluster.md, examples/kubernetes/rc/stolon-keeper0.yaml, examples/kubernetes/rc/stolon-keeper1.yaml, examples/kubernetes/statefulset/stolon-keeper.yaml, tests/integration/ha_test.go, tests/integration/init_test.go, tests/integration/utils.go
Also add stolon-keeper `--uid` option and deprecate `--id`.
=> cmd: rename various occurences of id to uid

README.md, doc/README.md, doc/faq.md
Merge and update #164 and #172.
=> doc: Improve faq section.

build, examples/docker/.gitignore, examples/docker/Dockerfile-Keeper, examples/docker/Dockerfile-Proxy, examples/docker/Dockerfile-Sentinel, examples/docker/Makefile, examples/docker/README.md, examples/docker/etc/init-spec.json, examples/docker/etc/keeper-entrypoint.sh, examples/docker/local-clean.sh, examples/docker/local-up.sh
Not sure if this will be helpful, I added an example of running stolon cluster with Docker Network. More information can be found in the README.
I'm also currently testing it with Docker Compose; then later Swarm.
=> Stolon cluster with Docker Network.

examples/kubernetes/rc/stolon-keeper0.yaml, examples/kubernetes/statefulset/stolon-keeper.yaml
=> k8s examples: set the right data dir

cmd/keeper/keeper.go, cmd/proxy/proxy.go, cmd/sentinel/sentinel.go
after the migration to zap we lost some os.Exit at startup.
=> cmds: Fix missing exit after error

cmd/keeper/keeper.go, cmd/keeper/keeper_test.go
=> Fix incorrect parsing of synchronous_standby_names for postgres 9.6

cmd/keeper/keeper.go, common/common.go, licenses/LICENSE-BSD-3-Clause
=> keeper: write files atomically

cmd/proxy/proxy.go
after adding the timeout timer, stop/startPollonProxy and
sendPollonConfData can be called concurrently from different
goroutines. This patch adds a mutex inside them.
=> proxy: fix data race

cmd/stolonctl/clusterdata.go
Add a stolonctl command to display current clusterdata.
=> stolonctl: add clusterdata command

cmd/keeper/keeper.go, doc/cluster_spec.md, pkg/cluster/cluster.go
add various postgresql recovery target settings for point in time
recovery:
recovery_target
recovery_target_lsn
recovery_target_name
recovery_target_time
recovery_target_xid
recovery_target_timeline
=> cluster: add pitr recovery target settings

cmd/stolonctl/status.go
report db status and if no db is assigned to a keeper.
=> stolonct: status: report db status

examples/kubernetes/README.md, examples/kubernetes/rc/README.md, examples/kubernetes/statefulset/stolon-keeper.yaml
* Deprecate replication controller example and explain the reasons.
* Update statefulset controller example uncommenting StatefulSet Kind instead of
PetSet Kind
=> examples: update k8s examples

glide.lock, glide.yaml, vendor/github.com/sorintlab/pollon/pollon.go, vendor/github.com/sorintlab/tcpkeepalive/LICENSE
=> proxy: vendor updated pollon

cmd/stolonctl/removekeeper.go, cmd/stolonctl/status.go, tests/integration/ha_test.go
Add related integration tests
Thanks-to: Sergey Volkovich
/cc @sergik
=> stolonctl: add removekeeper command

examples/kubernetes/statefulset/README.md, examples/kubernetes/statefulset/postgresql_upgrade.md
Provide an example of upgrade from PostgreSQL 9.6 to PostgreSQL 10.0 when running on Kubernetes.
=> Add example for major postgresql upgrade on k8s

tests/integration/standby_test.go
Like done in other tests use waitKeeperReady that will also check if the
clusterdata reports the keeper as initialized or WaitDBUP may catch the db up
when it's instead initializing (if starts and stop few times).
=> tests: use waitKeeperReady instead of WaitDBUP.

cmd/keeper/keeper.go, cmd/proxy/proxy.go, cmd/sentinel/sentinel.go, pkg/postgresql/postgresql.go, pkg/postgresql/utils.go
* Move to stdlib context
* Use context cancel function instead of closing a stop channel.
=> *: improve context usage on process shutdown

cmd/keeper/keeper.go, doc/faq.md
And explain why we don't use postgres FIRST or ANY methods with N different than
the number of the wanted synchronous standbys but we have a different logic to
maintain consistency.
=> *: document how we use synchronous_standby_names syntax

pkg/store/store.go
=> store: fix etcdv3 election get leader timeout

cmd/keeper/keeper.go, pkg/postgresql/postgresql.go
Add a StopIfStarted method to be able to call Stop without getting an error if
the instance isn't started.
Always check errors when stopping an instance if we require that it should be
stopped.
=> keeper: improve postgres instance stop

doc/README.md, doc/ssl.md
=> doc: add postgresl SSL setup

cmd/keeper/cmd/keeper.go, pkg/postgresql/postgresql.go
To avoid replica creation failing due to removed wal on the source.
Also double the number of wal senders since wal streaming will use an additional
wal sender.
On postgres >= 9.6 we'll provide a replication slot to use.
Note that on postgres 10 we could avoid passing a replication slot since it'll
create a temporary one. For the moment use the persistent replication slot that
will be created by the keeper on the instance also on postgres 10. Sometimes the
initial pg_basebackup will fail if the replication slot is not yet created but
the successive try will succeed.
=> keeper: use wal streaming during pg_basebackup

pkg/store/libkv.go
convert libkv.ErrKeyModified to store.ErrKeyModified
=> store: handle libkv ErrKeyModified

build, cmd/stolonctl/cmd/promote.go, cmd/stolonctl/cmd/update.go, test
test all the packages without the need to provide a list
=> test: improve test script

cmd/keeper/cmd/keeper.go
improve the in memory dbLocalState management forcing its update only after
being written to the local state file. In such way we'll only report the current
generation, dbuid etc... to the sentinel only after we are sure we have saved it
locally.
=> keeper: update in memory dbLocalState only after saving on disk

doc/stolonctl.md
Clarify some of the options and the wording.
Fixes #511
=> updated stolonctl doc

doc/standbycluster.md, doc/syncrepl.md
* Update to new v0.13.0 standbyconfig settings
* Update the examples to use etcdv3 store like in the other examples.
=> doc: update standbycluster and syncrepl doc

cmd/keeper/cmd/keeper.go, tests/integration/config_test.go
This pull request is here to allow separate configuration for listen address and advertise address.
This is the same pull request as here (but fixed for master branch):
https://github.com/sorintlab/stolon/pull/455 .
=> Add advertise address and port config

.travis.yml, go.sum, test
Update travis and use external go vet shadow tools since it's not included in
the go vet command
=> *: update to go1.12

tests/integration/config_test.go
My fault since I disabled github option to require branches to be up to date
before merging to avoid asking people to always rebase after every PR merge...
=> tests: fix missing rebase of PR #668

internal/postgresql/postgresql.go
These two changes cause `pg_basebackup` to log the names of the files it is processing, along with the estimated progress through the entire backup. For large databases this can be very useful in estimating how long the backup will take.
=> Enable verbose & progress logging for pg_basebackup

cmd/stolonctl/cmd/removekeeper.go, internal/cluster/cluster_test.go
Tasks:
1) Reuse the method FindDB
2) Add test coverage for method FindDB
=> Reusing FindDB method and added test for the same

build
=> Show verbal progress in the build script

cmd/keeper/cmd/keeper.go, cmd/keeper/cmd/keeper_test.go, cmd/proxy/cmd/proxy.go, cmd/sentinel/cmd/sentinel.go, cmd/stolonctl/cmd/clusterdata.go, cmd/stolonctl/cmd/init.go, cmd/stolonctl/cmd/stolonctl.go, cmd/stolonctl/cmd/update.go, internal/cluster/cluster.go, internal/cluster/v0/clusterview.go, internal/postgresql/connstring.go, internal/postgresql/postgresql.go, internal/postgresql/utils.go, internal/store/k8s.go, internal/store/kvbacked.go, internal/timer/timer_linux.go, internal/util/slice.go, scripts/gen_commands_doc.go, test, tests/integration/ha_test.go, tests/integration/init_test.go, tests/integration/pitr_test.go, tests/integration/sentinel_test.go, tests/integration/standby_test.go, tests/integration/utils.go
* Run golangci-lint in test script
* Fix all linting errors
=> *: use golangci-lint

README.md
add PostgreSQL 12 in requirements section
=> README: update requirements section

internal/cluster/cluster.go, internal/postgresql/postgresql.go
SyncTimeout is currently undocumented and is set to 30 minutes causing
unexpected behaviors to users.
So make its default set to 0 (infinite).
Another PR will document it.
=> cluster: make DefaultSyncTimeout infinite.

README.md
Add stolon community forum (https://talk.stolon.io) in place of the mailing list
and the gitter channel.
=> readme: update contacts section

tests/integration/utils.go
since latest etcdv3 client will not fail on connection errors but will retry
until context timeout, shorten it to 1 second in WaitUp/WaitDown test store
functions.
=> tests: use test store context timeout

.agola/config.jsonnet, examples/kubernetes/image/docker/Dockerfile, test
* Update to go 1.14
* Update golangci-lint to v1.23.6 that works with go 1.14
=> *: update to go 1.14

.agola/config.jsonnet, scripts/agola-k8s.sh
Update bsycorp/kind image to v1.19.4 to follow latest available k8s release.
=> agola ci: update bsycorp/kind image to v1.19.4

internal/postgresql/utils.go
* This change disable Postgres to print out password to logs even log_statement is something else than none (default)
Below is explained what happens when user is created or altered
1. Transaction is created when starting to manipulate password for the user
2. Logs are disabled by setting `log_statement` to `none` during the transaction
Because logs are disable during the transaction, passwords are not visible in logs at all.
=> Issue #793 - Hide root & replication users password from Postgres logs

examples/kubernetes/role-binding.yaml, examples/kubernetes/role.yaml
update rbac apiVersion fixing this issue [#889](https://github.com/sorintlab/stolon/issues/889)
=> Update rbac apiVersion for k8s deployment

.agola/config.jsonnet, scripts/agola-k8s.sh
Latest version has less issues and looks more stable.
=> ci: update bsycorp/kind to latest version
